site_name: Мастер-класс по docs-as-code # Название сайта
site_description: Мои материалы для мастер-класса по docs-as-code # Описание сайта, добавляется в meta-теги

theme:
  name: material
  features:
  - navigation.tabs
  logo: images/logo.png
  font:
    text: Roboto
    code: Roboto Mono
  language: ru
  palette:
    - scheme: my-scheme

features:
    - navigation.sections
    - navigation.path
    - navigation.indexes
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - toc.integrate
    - navigation.instant
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

nav:
  - Главная: index.md
  - Конспекты:
      - study-notes/1-webinar-notes.md
      - study-notes/2-webinar-notes.md
      - study-notes/3-webinar-notes.md
      - study-notes/4-webinar-notes.md
      - study-notes/5-webinar-notes.md
  - Работы:
      - assignments/telegram-instruction.md
      - assignments/obsidian-instruction.md
      - assignments/use-case.md
      - API-документация: assignments/api-doc.md
  - Полезные материалы:
      - resources/mkdocs-yml.md
      - resources/markdown.md

markdown_extensions:
  - admonition
  - footnotes
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tilde
  - pymdownx.mark
  - pymdownx.caret
  - pymdownx.snippets

plugins:
  - search
  - glightbox
  - swagger-ui-tag
  - plantuml:
      puml_url: https://www.plantuml.com/plantuml/
      theme:
        enabled: false

extra_css:
  - stylesheets/extra.css